# Generated by Django 4.2.6 on 2024-12-25 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('type', models.CharField(choices=[('0.25', 'One week'), ('1', 'One month'), ('2', 'Two months'), ('3', 'Three months'), ('6', 'Six months'), ('12', 'Twelve months')], max_length=6, unique=True, verbose_name='Subscription type')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
                ('selling_price', models.PositiveIntegerField(default=0, verbose_name='Selling price')),
                ('promo', models.BooleanField(default=False, verbose_name='Promo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Expire date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ('-id',),
            },
        ),
    ]
