# Generated by Django 4.2.6 on 2024-12-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_activity', models.CharField(choices=[('catering', 'Catering'), ('other', 'Other')], max_length=25, verbose_name='Field of Activity')),
                ('work_experience', models.CharField(max_length=20, verbose_name='Work Experience')),
                ('work_shift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Shift')),
                ('number_of_staff', models.IntegerField(verbose_name='Number of staff')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('personnel_training', models.TextField(blank=True, null=True, verbose_name='Personnel Training Detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Counseling',
                'verbose_name_plural': 'Counselings',
            },
        ),
    ]
