# Generated by Django 4.2.6 on 2025-04-03 15:06

import apps.ticket.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-id',), 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.ticket.utils.ticket_file_src, verbose_name='فایل مرتبط'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('close', 'بسته شده')], default='open', max_length=32, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('general', 'مشکل عمومی/پیشنهاد'), ('technical', 'مشکل فنی')], default='general', max_length=64, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
    ]
