# Generated by Django 4.2.6 on 2024-12-25 14:44

import apps.course.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(default='No title', max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('short_des', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short description')),
                ('description', tinymce.models.HTMLField(default='', verbose_name='Description')),
                ('type', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=32, verbose_name='Course type')),
                ('duration', models.CharField(help_text='2h, 30m', max_length=128, verbose_name='بازهٔ زمانی')),
                ('payment_type', models.CharField(choices=[('free', 'Free'), ('cash', 'Cash')], default='cash', max_length=32, verbose_name='Payment type')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Price')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('selling_price', models.PositiveBigIntegerField(default=0, verbose_name='Selling price')),
                ('introduction_video', models.FileField(blank=True, null=True, upload_to=apps.course.utils.introduction_video_path, verbose_name='Introduction video')),
                ('introduction_video_link', models.URLField(blank=True, null=True, verbose_name='Introduction video')),
                ('introduction_image', models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='Introduction image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='تصویر')),
                ('pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(default='No name', max_length=128, verbose_name='Instructor name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('image', models.ImageField(upload_to='images/instructors/', verbose_name='Profile pic')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin url')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram url')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='X/Twitter url')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website url')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='course.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'User course',
                'verbose_name_plural': 'User courses',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(default='No title', max_length=255, verbose_name='Session title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course session',
                'verbose_name_plural': 'Course sessions',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('question', models.CharField(max_length=255, verbose_name='Question title')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(default='No title', max_length=255, verbose_name='Episode title')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Episode number')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.course.utils.course_video_path, verbose_name='Video file')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='File url')),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Minutes', null=True, verbose_name='بازهٔ زمانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.course', verbose_name='Course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.instructor', verbose_name='Instructor'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('text', models.TextField(max_length=512)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.course', verbose_name='Course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='course.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Course comment',
                'verbose_name_plural': 'Course comments',
            },
        ),
    ]
