# Generated by Django 4.2.6 on 2025-04-03 15:05

import apps.course.utils
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('name', models.CharField(max_length=150, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت\u200cهای دوره'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'قسمت', 'verbose_name_plural': 'قسمت ها'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرسین'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'جلسه دوره', 'verbose_name_plural': 'جلسات دوره'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': 'دوره\u200c کاربر', 'verbose_name_plural': 'دوره\u200cهای کاربران'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='۲ ساعت و ۳۰ دقیقه', max_length=128, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.instructor', verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.course.utils.course_images_path, verbose_name='تصویر معرفی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.course.utils.introduction_video_path, verbose_name='ویدیو معرفی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='introduction_video_link',
            field=models.URLField(blank=True, null=True, verbose_name='ویدیو معرفی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='course',
            name='payment_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('cash', 'نقدی')], default='cash', max_length=32, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='selling_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=128, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('in_person', 'حضوری'), ('online', 'سمینار'), ('offline', 'غیر حضوری')], default='offline', max_length=32, verbose_name='نوع دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='دقیقه', null=True, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.course.utils.course_video_path, verbose_name='فایل ویدیو'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک فایل'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='شماره قسمت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='course.session', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان قسمت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='عنوان سوًال'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='معرفی کوتاه'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(upload_to='images/instructors/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(default='بدون نام', max_length=128, verbose_name='نام مدرس'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس توییتر/x'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255, verbose_name='عنوان جلسه'),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='course.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='تمام شده'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='course.coursecategory', verbose_name='دسته'),
            preserve_default=False,
        ),
    ]
