# Generated by Django 4.2.6 on 2025-04-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursecategory_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='icon',
            field=models.ImageField(default=1, upload_to='images/icon_category_course/', verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
