# Generated by Django 4.2.6 on 2024-12-25 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('type', models.CharField(choices=[('MOBILE_VERIFICATION_CODE', 'Mobile verification code'), ('SUBSCRIPTION_END_WARNING', 'Subscription end warning'), ('NEW_COUNSELING_FORM_SUBMITED_ADMIN', 'New counseling form submited')], max_length=128, verbose_name='Notif type')),
                ('title', models.CharField(max_length=255, verbose_name='Notif title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notif description')),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='images/notifications/')),
                ('kwargs', models.JSONField(blank=True, null=True, verbose_name='KeyWord args')),
                ('send_notify', models.BooleanField(default=True, verbose_name='Send Notify')),
                ('is_showing', models.BooleanField(default=True, verbose_name='Is showing')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='To user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-id',),
            },
        ),
    ]
