# Generated by Django 4.2.6 on 2024-12-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(default='No title', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/index/', verbose_name='Video cover')),
                ('video', models.FileField(blank=True, null=True, upload_to='images/index/', verbose_name='Video')),
                ('video_url', models.URLField(default='', verbose_name='Video url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Index video',
                'verbose_name_plural': 'Index Videos',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Related link')),
                ('image', models.ImageField(upload_to='images/banners/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('-id',),
            },
        ),
    ]
